<html>

<head>
    <link rel="stylesheet" type="text/css" href="css/portada/portada.css">
    <link rel="stylesheet" type="text/css" href="css/portada/default.css" />
    <link rel="stylesheet" type="text/css" href="css/portada/component.css" />
    <script src="js/Portada/modernizr.custom.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="js/Portada/jquery.lettering.js"></script>
    <meta charset="utf-8">
    <title>UniCloud</title>

</head>

<body>
    <div id="wrapper">

        <div class="os-phrases" id="os-phrases">
            <h2>No temas por tus archivos</h2>
            <h2>Gestiona todo en la nube</h2>
            <h2>Todo en un mismo sitio</h2>
            <h2>UNIVERSAL CLOUD</h2>
            <h2>UNIVERSAL CLOUD</h2>
        </div>

        <script>
            $(document).ready(function () {
                $("#os-phrases > h2").lettering('words').children("span").lettering().children("span").lettering();
            })
        </script>
        <div class="sky">
            <div class="clouds_one"></div>
            <div class="clouds_two"></div>
            <div class="clouds_three"></div>
        </div>

        <div id="formularios">

            <div id="div-login">

                <h1>UNIVERSAL CLOUD</h1>

                <h3>LOGIN</h3>
                <form id="formulario-login" enctype="multipart/form-data" method="post" name="formulario-login">
                    <label id="luser" for="user">Nick:</label>
                    <input id="user" type="text" name="user">
                    <label id="lpass" for="pass">Contraseña:</label>
                    <input id="pass" type="password" name="pass">
                    <input id="button" type="submit" value="Log In">
                </form>
            </div>
            <div id="spacer" style="width:20px;"></div>
            <div id="div-registro" >
                <form id="formulario-registro" enctype="multipart/form-data" method="post" name="formulario-registro">
                    <label id="luser" for="nick">Nick:</label>
                    <input id="nickr" type="text" name="nick">
                    <label id="lnombre" for="nombre">Nombre:</label>
                    <input id="nombrer" type="text" name="nombre">
                    <label id="lpass" for="pass">Contraseña:</label>
                    <input id="passr" type="password" name="pass">
                    <label id="lpass" for="txtpass">Comfirmar Contraseña:</label>
                    <input id="txtpassr" type="password" name="txtpass">
                    <label id="lemail" for="email">Email:</label>
                    <input id="emailr" type="text" name="email">
                    <input type="submit" id="button" value="Sign In">
                </form>
            </div>
            <br>
            <div id="resultado">
            </div>

        </div>
        <div id="botones">
            <button id="boton-login-registro">Saltar Intro</button>
        </div>


        <!--           SCRIPTS           -->
        <script src="js/Portada/saltar_intro.js" type="text/javascript"></script>
        <script src="js/Portada/ajax-formularios.js" type="text/javascript"></script>

    </div>
</body>

</html>